import { CheckIn, SupportResource, UserProfile } from '../types';

export const INITIAL_USER: UserProfile = {
  id: 'usr-default-demo',
  email: 'survivor.support@example.org',
  displayName: 'Alex Morgan',
  ageRange: '25-34',
  preferredLanguage: 'en',
  timezone: 'UTC',
  notificationEnabled: true,
  consentGiven: true,
  consentDate: new Date(Date.now() - 14 * 86400000).toISOString(),
  consentVersion: 'v1.0-2025',
  createdAt: new Date(Date.now() - 30 * 86400000).toISOString()
};

// 14 days of realistic longitudinal check-in data to visualize trends
export const SEED_CHECK_INS: CheckIn[] = [
  {
    id: 'chk-14',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 13 * 86400000).toISOString().split('T')[0],
    mood: 7,
    stress: 4,
    anxiety: 3,
    sleepQuality: 8,
    energy: 7,
    socialConnection: 7,
    dailyFunctioning: 8,
    journalText: 'Felt relatively calm today. Went for a brisk morning walk and had a peaceful breakfast.',
    createdAt: new Date(Date.now() - 13 * 86400000).toISOString()
  },
  {
    id: 'chk-13',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 12 * 86400000).toISOString().split('T')[0],
    mood: 6,
    stress: 5,
    anxiety: 4,
    sleepQuality: 7,
    energy: 6,
    socialConnection: 6,
    dailyFunctioning: 7,
    journalText: 'A bit busy with work deadlines, but manageable so far.',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString()
  },
  {
    id: 'chk-12',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 11 * 86400000).toISOString().split('T')[0],
    mood: 6,
    stress: 5,
    anxiety: 4,
    sleepQuality: 7,
    energy: 6,
    socialConnection: 6,
    dailyFunctioning: 7,
    createdAt: new Date(Date.now() - 11 * 86400000).toISOString()
  },
  {
    id: 'chk-11',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
    mood: 5,
    stress: 6,
    anxiety: 5,
    sleepQuality: 6,
    energy: 5,
    socialConnection: 5,
    dailyFunctioning: 6,
    journalText: 'Felt some tension in the afternoon. Tried to do some deep breathing exercises.',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString()
  },
  {
    id: 'chk-10',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 9 * 86400000).toISOString().split('T')[0],
    mood: 5,
    stress: 6,
    anxiety: 6,
    sleepQuality: 5,
    energy: 5,
    socialConnection: 5,
    dailyFunctioning: 6,
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString()
  },
  {
    id: 'chk-9',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 8 * 86400000).toISOString().split('T')[0],
    mood: 4,
    stress: 7,
    anxiety: 6,
    sleepQuality: 5,
    energy: 4,
    socialConnection: 4,
    dailyFunctioning: 5,
    journalText: 'Sleep was broken last night due to bad dreams. Feeling somewhat drained today.',
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString()
  },
  {
    id: 'chk-8',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
    mood: 4,
    stress: 7,
    anxiety: 7,
    sleepQuality: 4,
    energy: 4,
    socialConnection: 4,
    dailyFunctioning: 5,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString()
  },
  {
    id: 'chk-7',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 6 * 86400000).toISOString().split('T')[0],
    mood: 4,
    stress: 8,
    anxiety: 7,
    sleepQuality: 4,
    energy: 3,
    socialConnection: 3,
    dailyFunctioning: 4,
    journalText: 'Hard to focus on simple daily chores today. Kept postponing errands.',
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString()
  },
  {
    id: 'chk-6',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    mood: 3,
    stress: 8,
    anxiety: 8,
    sleepQuality: 3,
    energy: 3,
    socialConnection: 3,
    dailyFunctioning: 4,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString()
  },
  {
    id: 'chk-5',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
    mood: 4,
    stress: 7,
    anxiety: 7,
    sleepQuality: 4,
    energy: 4,
    socialConnection: 4,
    dailyFunctioning: 4,
    journalText: 'Talked to my sister on the phone for 15 minutes. It felt comforting to hear a friendly voice.',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString()
  },
  {
    id: 'chk-4',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    mood: 4,
    stress: 7,
    anxiety: 6,
    sleepQuality: 5,
    energy: 4,
    socialConnection: 5,
    dailyFunctioning: 5,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString()
  },
  {
    id: 'chk-3',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    mood: 5,
    stress: 6,
    anxiety: 6,
    sleepQuality: 6,
    energy: 5,
    socialConnection: 5,
    dailyFunctioning: 6,
    journalText: 'Taking small steps. Managed to cook a nutritious meal and rested in the afternoon.',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString()
  },
  {
    id: 'chk-2',
    userId: 'usr-default-demo',
    date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
    mood: 5,
    stress: 6,
    anxiety: 5,
    sleepQuality: 6,
    energy: 5,
    socialConnection: 6,
    dailyFunctioning: 6,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString()
  },
  {
    id: 'chk-1',
    userId: 'usr-default-demo',
    date: new Date().toISOString().split('T')[0],
    mood: 6,
    stress: 5,
    anxiety: 5,
    sleepQuality: 7,
    energy: 6,
    socialConnection: 6,
    dailyFunctioning: 7,
    journalText: 'Today feels slightly clearer. Recognizing my stress triggers helps me pause before feeling overwhelmed.',
    createdAt: new Date().toISOString()
  }
];

export const VERIFIED_SUPPORT_RESOURCES: SupportResource[] = [
  {
    id: 'res-988',
    name: '988 Suicide & Crisis Lifeline',
    description: 'Free, confidential support available 24/7 in the United States and Canada for anyone in suicidal crisis or emotional distress.',
    resourceType: 'crisis_hotline',
    countryCode: 'US',
    phone: '988',
    website: 'https://988lifeline.org',
    availableHours: '24/7 / 365 Days',
    isEmergency: true,
    badges: ['Toll-free', 'Confidential', 'Phone & Chat']
  },
  {
    id: 'res-textline',
    name: 'Crisis Text Line',
    description: 'Free 24/7 text-based crisis support by trained volunteer crisis counselors.',
    resourceType: 'text_line',
    countryCode: 'GLOBAL',
    phone: 'Text HOME to 741741 (US/CA) or 85258 (UK)',
    website: 'https://www.crisistextline.org',
    availableHours: '24/7 Continuous',
    isEmergency: true,
    badges: ['Text Only', 'Free', 'Anonymous']
  },
  {
    id: 'res-trevor',
    name: 'The Trevor Project',
    description: 'Crisis intervention and suicide prevention services for LGBTQ young people under 25.',
    resourceType: 'crisis_hotline',
    countryCode: 'US',
    phone: '1-866-488-7386',
    website: 'https://www.thetrevorproject.org',
    availableHours: '24/7',
    isEmergency: true,
    badges: ['LGBTQ+ Safe', 'Youth Focused', 'Call & Text']
  },
  {
    id: 'res-samaritans',
    name: 'Samaritans (UK & Ireland)',
    description: 'Round-the-clock listening service for anyone who is struggling to cope, who needs someone to listen without judgment.',
    resourceType: 'crisis_hotline',
    countryCode: 'GB',
    phone: '116 123',
    website: 'https://www.samaritans.org',
    availableHours: '24/7',
    isEmergency: true,
    badges: ['UK & Ireland', 'Freephone']
  },
  {
    id: 'res-befrienders',
    name: 'Befrienders Worldwide',
    description: 'Global network of 349 emotional support centres across 32 countries helping people who are in despair or contemplating suicide.',
    resourceType: 'organization',
    countryCode: 'GLOBAL',
    website: 'https://www.befrienders.org',
    availableHours: 'Varies by chapter',
    isEmergency: false,
    badges: ['International', 'Multilingual Directory']
  },
  {
    id: 'res-iasp',
    name: 'International Association for Suicide Prevention (IASP)',
    description: 'Official directory of verified crisis helplines and survivor support resources in over 50 countries worldwide.',
    resourceType: 'emergency',
    countryCode: 'GLOBAL',
    website: 'https://www.iasp.info/resources/Crisis_Centres',
    availableHours: 'Online Directory',
    isEmergency: false,
    badges: ['Global Directory', 'Verified']
  }
];
